file:
  storage:
    location: Images

spring:
  servlet:
    multipart:
      enabled: true
      location: temp123
      file-size-threshold: 5MB
      max-file-size: 1MB
      max-request-size: 20MB